data = [
    ["Liam", "Anderson", 28, "Canadian"],
    ["Emma", "Brown", 34, "British"],
    ["Noah", "Clark", 22, "American"],
    ["Olivia", "Davis", 30, "Australian"],
    ["William", "Evans", 41, "Irish"],
    ["Ava", "Foster", 26, "New Zealander"],
    ["James", "Garcia", 37, "Mexican"],
    ["Sophia", "Harris", 29, "South African"],
    ["Benjamin", "Ivanov", 45, "Russian"],
    ["Isabella", "Johnson", 31, "American"],
    ["Lucas", "Kim", 24, "South Korean"],
    ["Mia", "Lopez", 33, "Spanish"],
    ["Henry", "Martinez", 27, "Argentinian"],
    ["Charlotte", "Nguyen", 36, "Vietnamese"],
    ["Alexander", "Olsen", 39, "Norwegian"],
    ["Amelia", "Patel", 23, "Indian"],
    ["Daniel", "Quinn", 44, "Scottish"],
    ["Harper", "Roberts", 32, "Welsh"],
    ["Matthew", "Silva", 38, "Brazilian"],
    ["Evelyn", "Taylor", 25, "American"],
    ["Joseph", "Usman", 40, "Nigerian"],
    ["Abigail", "Valdez", 21, "Colombian"],
    ["Samuel", "White", 35, "American"],
    ["Ella", "Xu", 28, "Chinese"],
    ["David", "Young", 42, "American"],
]